#!/bin/bash

echo -e "\n-- Installing GitHub CLI --\n"

# Copy keyring
curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | \
  sudo dd of=/etc/apt/trusted.gpg.d/githubcli-archive-keyring.gpg

# Add  repo to apt
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/trusted.gpg.d/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | \
  sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null

# Install
sudo apt update
sudo apt install gh
