#!/bin/bash
# Install Miniconda3
# From https://docs.anaconda.com/miniconda/

mkdir -p "$HOME"/miniconda3
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O "$HOME"/miniconda3/miniconda.sh
bash "$HOME"/miniconda3/miniconda.sh -b -u -p "$HOME"/miniconda3
rm -rf "$HOME"/miniconda3/miniconda.sh

# Initialize conda for bash and set default to not activate conda on startup
"$HOME"/miniconda3/bin/conda init bash
"$HOME"/miniconda3/bin/conda config --set auto_activate_base false
