#!/bin/bash
# From https://docs.anaconda.com/miniconda/
# Changed ~ for $HOME

echo -e "\n-- Installing Miniconda3 --\n"

mkdir -p "$HOME"/miniconda3
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O "$HOME"/miniconda3/miniconda.sh
bash "$HOME"/miniconda3/miniconda.sh -b -u -p "$HOME"/miniconda3
rm -rf "$HOME"/miniconda3/miniconda.sh

# Set default to not activate conda on startup
conda config --set auto_activate_base false
