#!/bin/bash
# Install Node.js via nvm

# Download and install nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash

# Source nvm script
\. "$HOME/.nvm/nvm.sh"

# Install Node.js 23
nvm install 23

# Verify installation
node -v
nvm current
npm -v
