#!/bin/bash

echo -e "\n-- Installing sops --\n"

# Install sops
## Download and install sops
curl -sSLO "https://github.com/getsops/sops/releases/download/v3.9.3/sops-v3.9.3.linux.amd64"
sudo mv "sops-v3.9.3.linux.amd64" "/usr/local/bin/sops"
sudo chmod +x "/usr/local/bin/sops"

## Verify checksums
curl -sSLO https://github.com/getsops/sops/releases/download/v3.9.3/sops-v3.9.3.checksums.txt
curl -sSLO https://github.com/getsops/sops/releases/download/v3.9.3/sops-v3.9.3.checksums.pem
curl -sSLO https://github.com/getsops/sops/releases/download/v3.9.3/sops-v3.9.3.checksums.sig

cosign verify-blob sops-v3.9.3.checksums.txt \
  --certificate sops-v3.9.3.checksums.pem \
  --signature sops-v3.9.3.checksums.sig \
  --certificate-identity-regexp=https://github.com/getsops \
  --certificate-oidc-issuer=https://token.actions.githubusercontent.com

rm sops-v3.9.3.checksums.txt sops-v3.9.3.checksums.pem sops-v3.9.3.checksums.sig
